language: python

before_install:
  - git config --global user.name "Yihui Xie"
  - git config --global user.email "xie@yihui.name"
  - sudo apt-get update -qq
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-get update -qq
  - sudo apt-get build-dep -y r-base

install:
  - ./install-r-devel

script:
  - ~/R-devel/bin/Rscript -e "sessionInfo()"

